tasks:
  - init: yarn install && yarn run build
    command: yarn start

vscode:
  extensions:
    - rocketseat.RocketseatReactJS@2.2.0:CMZI2JF+9mcg15CoJkRPOQ==
    - wix.vscode-import-cost@2.12.0:Z31eYgMsqJCLYkcg0s66Ug==